api/urls.py
from django.urls import path

from . import views

complete_translatable_path = (
    "modules/<name:module_name>/branches/<path:branch_name>/domains/<name:domain_name>/languages/<locale:lang>"
)

urlpatterns = [
    path("", views.APIHomeView.as_view(), name="api-v1-home"),
    # Liveliness checks
    path("check/", views.check, name="api-v1-check"),
    # Modules
    path("modules/", views.ModulesView.as_view(), name="api-v1-list-modules"),
    path("modules/<name:module_name>", views.ModuleView.as_view(), name="api-v1-info-module"),
    path(
        "modules/<name:module_name>/branch/<path:branch_name>",
        views.ModuleBranchView.as_view(),
        name="api-v1-info-module-branch",
    ),
    # Teams
    path("teams/", views.TeamsView.as_view(), name="api-v1-list-teams"),
    path("teams/<locale:team_name>", views.TeamView.as_view(), name="api-v1-info-team"),
    # Languages
    path("languages/", views.LanguagesView.as_view(), name="api-v1-list-languages"),
    # Releases
    path("releases/", views.ReleasesView.as_view(), name="api-v1-list-releases"),
    path("releases/<name:release>", views.ReleaseView.as_view(), name="api-v1-info-release"),
    path("releases/<name:release>/stats", views.ReleaseStatsView.as_view(), name="api-v1-info-release-stats"),
    path(
        "releases/<name:release>/languages/<locale:locale>",
        views.ReleaseLanguageView.as_view(),
        name="api-v1-info-release-language",
    ),
    # Vertimus workflow
    path(complete_translatable_path, views.ModuleLangStatsView.as_view(), name="api-v1-module-in-lang-statistics"),
    # APIs to reserve translation and upload translation, as could be used by an external translation tool.
    path(
        f"{complete_translatable_path}/reserve", views.ReserveTranslationView.as_view(), name="api-v1-reserve-module"
    ),
    path(f"{complete_translatable_path}/upload", views.UploadTranslationView.as_view(), name="api-v1-upload-file"),
    # Notifications from the software forge. Read the documentation to see how to trigger this endpoint.
    path(
        "modules/<name:module_name>/branches/<path:branch_name>/ping",
        views.refresh_module_branch,
        name="api-v1-refresh-module-branch",
    ),
]

damnedlies/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path, register_converter
from django.urls.converters import StringConverter
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from django.views.static import serve

from common import views as common_views
from stats import views as stats_views


class LocaleConverter(StringConverter):
    regex = "[-_a-zA-Z@]+"


class NameConverter(StringConverter):
    """Converter for module, branch, or domain names."""

    regex = r"[-~\w\+\.]+"


register_converter(LocaleConverter, "locale")
register_converter(NameConverter, "name")
module_branch_domain = "<name:module_name>/<path:branch_name>/<name:domain_name>"

urlpatterns = [
    path("", common_views.index, name="home"),
    path("about/", common_views.about, name="about"),
    path("login/", common_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", require_POST(auth_views.LogoutView.as_view()), name="logout"),
    path("register/", common_views.site_register, name="register"),
    re_path(r"^help/(?P<topic>\w+)/(?P<modal>[0-1])?/?$", common_views.help_view, name="help"),
    path(
        "register/success/",
        TemplateView.as_view(template_name="registration/register_success.html"),
        name="register_success",
    ),
    path("register/activate/<slug:key>", common_views.activate_account, name="register_activation"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<slug:uidb64>/<slug:token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Webhook endpoint
    path("pull_code/", common_views.pull_code),
    path("teams/", include("teams.urls")),
    path("people/", include("people.urls")),
    # users is the hardcoded url in the contrib.auth User class, making it identical to /people
    path("users/", include("people.urls")),
    path("languages/", include("languages.urls")),
    path("vertimus/", include("vertimus.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("rss/", include("feeds.urls")),
    path("api/v1/", include("api.urls")),
]

urlpatterns += [
    re_path(r"^module/(?P<return_format>(html|json|xml))?/?$", stats_views.modules, name="modules"),
    path("module/po/%s/<filename>" % module_branch_domain, stats_views.dynamic_po, name="dynamic_po"),
    path("module/<name:module_name>/", stats_views.module, name="module"),
    path("module/<name:module_name>/edit/branches/", stats_views.module_edit_branches, name="module_edit_branches"),
    path("branch/<int:branch_id>/refresh/", stats_views.branch_refresh, name="branch_refresh"),
    path(
        "module/<name:module_name>/<name:potbase>/<path:branch_name>/<locale:langcode>/images/",
        stats_views.docimages,
        name="docimages",
    ),
    re_path(r"^releases/(?P<format>(html|json|xml))?/?$", stats_views.releases, name="releases"),
    re_path(r"^releases/(?P<release_name>[\w-]+)/(?P<format>(html|xml))?/?$", stats_views.release, name="release"),
    path("releases/compare/<dtype>/<path:rels_to_compare>/", stats_views.compare_by_releases, name="release-compare"),
    # Ajax URLs
    path("module/<name:module_name>/branch/<path:branch_name>/", stats_views.ajax_module_branch, name="module_branch"),
]

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

if settings.STATIC_SERVE:
    urlpatterns += [
        path("media/<path:path>", serve, kwargs={"document_root": settings.MEDIA_ROOT}),
        path("POT/<path:path>", serve, kwargs={"document_root": settings.POT_DIR}),
        path("HTML/<path:path>", serve, kwargs={"document_root": settings.SCRATCHDIR / "HTML"}),
    ]

people/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from people import views

# Path order is really important here
urlpatterns = [
    path("detail_change/", login_required(views.PersonEditView.as_view()), name="person_detail_change"),
    path("password_change/", views.person_password_change, name="person_password_change"),
    path("create_token/", views.person_create_token, name="person_create_token"),
    path("delete_token/", views.person_delete_token, name="person_delete_token"),
    path("team_join/", views.person_team_join, name="person_team_join"),
    path("team_leave/<locale:team_slug>/", views.person_team_leave, name="person_team_leave"),
    path("<int:pk>/", views.PersonDetailView.as_view(), name="person_detail_id"),
    # Equivalent to the previous, but using username instead of user pk
    path("<slug>/", views.PersonDetailView.as_view(), name="person_detail_username"),
    path("", views.PeopleListView.as_view(), name="people"),
]

teams/models.py
from datetime import timedelta
from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone, translation
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy

from common.utils import send_mail
from people.models import Person

if TYPE_CHECKING:
    from languages.models import Language


class TeamManager(models.Manager):
    def all_with_coordinator(self: "TeamManager") -> QuerySet:
        """
        Returns all teams with the coordinator already prefilled. Use that
        function to reduce the size of extracted data and the numbers of objects
        built or use all_with_roles() if you need information about the other
        roles.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(role="coordinator")
        role_dict = {}

        for role in roles:
            role_dict.setdefault(role.team_id, []).append(role.person)

        for team in teams:
            try:
                team.roles = {"coordinator": role_dict[team.id]}
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams

    def all_with_roles(self: "TeamManager") -> QuerySet:
        """
        This method prefills team.coordinator/committer/reviewer/translator to
        reduce subsequent database access.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(is_active=True)
        role_dict = {}

        for role in roles:
            if role.team_id not in role_dict:
                role_dict[role.team_id] = [role]
            else:
                role_dict[role.team_id].append(role)

        for team in teams:
            try:
                for role in role_dict[team.id]:
                    team.fill_role(role.role, role.person)
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams


class Team(models.Model):
    """The lang_code is generally used for the name of the team."""

    name = models.CharField(max_length=80)
    description = models.TextField()
    use_workflow = models.BooleanField(default=True)
    presentation = models.TextField(blank=True, verbose_name=_("Presentation"))
    members = models.ManyToManyField(Person, through="Role", related_name="teams")
    webpage_url = models.URLField(null=True, blank=True, verbose_name=_("Web page"))
    mailing_list = models.EmailField(null=True, blank=True, verbose_name=_("Mailing list"))
    mailing_list_subscribe = models.URLField(null=True, blank=True, verbose_name=_("URL to subscribe"))
    objects = TeamManager()

    class Meta:
        db_table = "team"
        ordering = ("description",)

    def __init__(self: "Team", *args, **kwargs) -> None:  # noqa ANN003
        models.Model.__init__(self, *args, **kwargs)
        self.roles: dict[str, list[Person]] = {}

    def __str__(self: "Team") -> str:
        return self.description

    def get_absolute_url(self: "Team") -> str:
        return reverse("team_slug", args=[self.name])

    def can_edit(self: "Team", user: "Person") -> bool:
        """Return True if user is allowed to edit this team
        user is a User (from request.user), not a Person
        """
        return user.is_authenticated and user.username in [p.username for p in self.get_coordinators()]

    def fill_role(self: "Team", role: str, person: "Person") -> None:
        """Used by TeamManager to prefill roles in team"""
        if not self.roles:
            self.roles = {"coordinator": [], "committer": [], "reviewer": [], "translator": []}
        self.roles[role].append(person)

    def get_description(self: "Team") -> str:
        return _(self.description)

    def get_languages(self: "Team") -> tuple["Language"]:
        return tuple(self.language_set.all())

    def get_members_by_role_exact(self: "Team", role: str, only_active: bool = True) -> list[Person]:
        """Return a list of active members"""
        try:
            return self.roles[role]
        except KeyError:
            if only_active:
                members = Person.objects.filter(role__team__id=self.id, role__role=role, role__is_active=True)
            else:
                members = Person.objects.filter(role__team__id=self.id, role__role=role)
            return list(members)

    def get_coordinators(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("coordinator", only_active=False)

    def get_committers_exact(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("committer")

    def get_reviewers_exact(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("reviewer")

    def get_translators_exact(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("translator")

    def get_members_by_roles(self: "Team", roles: list[str], only_active: bool = True) -> list[Person]:
        """Requires a list of roles in argument"""
        try:
            members = []
            for role in roles:
                members += self.roles[role]
        except KeyError:
            if only_active:
                members = Person.objects.filter(role__team__id=self.id, role__role__in=roles, role__is_active=True)
            else:
                members = Person.objects.filter(role__team__id=self.id, role__role__in=roles)
        return list(members)

    def get_committers(self: "Team") -> list[Person]:
        return self.get_members_by_roles(["coordinator", "committer"])

    def get_reviewers(self: "Team") -> list[Person]:
        return self.get_members_by_roles(["coordinator", "committer", "reviewer"])

    def get_translators(self: "Team") -> list[Person]:
        """Don't use get_members_by_roles to provide an optimization"""
        try:
            members = []
            for role in ["coordinator", "committer", "reviewer", "translator"]:
                members += self.roles[role]
        except KeyError:
            # Not necessary to filter as for other roles
            members = list(self.members.all())
        return members

    def get_inactive_members(self: "Team") -> list[Person]:
        """Return the inactive members"""
        return list(Person.objects.filter(role__team__id=self.id, role__is_active=False))

    def send_mail_to_coordinator(
        self: "Team", subject: str, message: str, message_kwargs: dict[str, Any] | None = None
    ) -> None:
        """Send a message to the coordinator, in her language if available
        and if subject and message are lazy strings"""
        recipients = [pers.email for pers in self.get_coordinators() if pers.email]
        if not recipients:
            return
        with translation.override(self.language_set.first().locale):
            message = "%s\n--\n" % (message % (message_kwargs or {}),)  # noqa: UP031
            message += _("This is an automated message sent from %s.") % settings.SITE_DOMAIN
            send_mail(str(subject), message, to=recipients, headers={settings.EMAIL_HEADER_NAME: "coordinator-mail"})


class FakeTeam:
    """
    This is a class replacing a Team object when a language
    has no team attached.
    """

    fake = 1

    def __init__(self: "FakeTeam", language: "Language") -> None:
        self.language = language
        self.description = _("No team for locale %s") % self.language.locale

    def get_absolute_url(self: "FakeTeam") -> str:
        return reverse("team_slug", args=[self.language.locale])

    def can_edit(self: "FakeTeam", _: "Person") -> bool:  # noqa PLR6301
        return False

    def get_description(self: "FakeTeam") -> str:
        return self.language.locale

    def get_languages(self: "FakeTeam") -> str:
        return _(
            self.language,
        )

    def get_coordinators(self: "FakeTeam") -> list[Person]:  # noqa PLR6301
        return []


ROLE_CHOICES = (
    ("translator", gettext_lazy("Translator")),
    ("reviewer", gettext_lazy("Reviewer")),
    ("committer", gettext_lazy("Committer")),
    ("coordinator", gettext_lazy("Coordinator")),
)


class Role(models.Model):
    """
    This is the intermediary class between Person and Team to attribute roles to
    Team members.
    """

    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    role = models.CharField(max_length=15, choices=ROLE_CHOICES, default="translator")
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "role"
        unique_together = ("team", "person")

    def __str__(self: "Role") -> str:
        return f"{self.person.name} is {self.role} in {self.team.description} team"

    @classmethod
    def inactivate_unused_roles(cls: "Role") -> None:
        """Inactivate the roles when login older than 180 days"""
        last_login = timezone.now() - timedelta(days=30 * 6)
        cls.objects.filter(person__last_login__lt=last_login, is_active=True).update(is_active=False)

people/templates/people/_includes/person_contribution_activity.html
{% load stats_extras %}
{% load humanize %}
{% load vertimus %}

{% block extrahead %}
    <script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            $("#user-working-on-modules-table").tablesorter({
                headers: {
                    0: {sortInitialOrder: 'asc', sorter: "digit"},
                    1: {sorter: "text"},
                    3: {sorter: false},
                    4: {sorter: "text"}
                },
            });
        });
    </script>
{% endblock %}

{% if states %}
    <div class="d-flex justify-content-between">
        <h2 class="float-start">{% trans "Current activity" %}</h2>
        <div class="float-end">
            <a href="#" id="hide-completed-modules">{% trans "Hide completed modules" %}</a>
            <a href="#" id="show-completed-modules" style="display: none;">{% trans "Show completed modules" %}</a>
        </div>
    </div>

    <div class="table-responsive">
        <table id="user-working-on-modules-table" name="user-working-on-modules-table" class="stats table">
            <thead>
                <tr>
                    <th data-column="0">{% trans "Date" %}</th>
                    <th>{% trans "Module" %}</th>
                    <th>{% trans "Statistics" %}</th>
                    <th>{% trans "Graph" %}</th>
                    <th>{% trans "State" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for state, stats in states %}
                    <tr id="{{ state.id }}{% if stats.tr_percentage == 100 %}-complete{% endif %}"
                        {% if stats.tr_percentage == 100 %}class="completed-module"{% endif %}>
                        <td data-column="0">
                            <span class="d-none">{{ state.updated|date:"U" }}</span>
                            {% with date=state.updated|naturalday:"DATE_FORMAT" %}
                                {{ date }}
                            {% endwith %}
                        </td>
                        <td>
                            <a href="{{ state.get_absolute_url }}">
                                {{ state.branch.module.get_description }} - {{ state.branch.name }}
                                - {{ state.domain.get_description }} - {{ state.language.get_name }}
                            </a>
                        </td>
                        <td>{{ stats.tr_percentage|default:"0" }}%</td>
                        <td>
                            <div class="graph">{{ stats|vis_stats }}</div>
                        </td>
                        <td>
                            <span class="badge text-wrap {% get_badge_bg_from_vertimus_state state %}">{{ state.description }}</span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

people/templates/people/_includes/person_maintains_modules.html
<h2>{% trans "Module maintenance" %}</h2>
<ul id="list-person-maintains-modules" class="list-group">
    {% for module in person.maintains_modules.all %}
        <li id="person-maintains-module-{{ module.name|slugify }}" class="list-group-item">
            <a href="{{ module.get_absolute_url }}">{{ module.get_description }}</a>
        </li>
    {% endfor %}
</ul>

people/templates/people/_includes/person_overview.html
{# Variables $person and $printroles must be defined prior to calling this template #}
{# This template is included in person.html, team.html and language-release.html #}

{% load people %}

<div class="row">
    <div id="user_profile_image" class="col-2 align-middle">
        {{ person|people_image }}
    </div>
    <div class="col-10">
        <a class="name main_feature" href="{{ person.get_absolute_url }}">{{ person.name }}</a>
        <br>
        {% if person.webpage_url %}
            <strong>{% trans "Web:" %}</strong>
            <a class="url" href="{{ person.webpage_url }}">{{ person.webpage_url }}</a>
            <br>
        {% endif %}

        {% if person.no_spam_email %}
            <strong>{% trans "Email address:" %}</strong>
            <a class="email" href="mailto:{{ person.no_spam_email }}">
                {{ person.no_spam_email }}
            </a>
            <br>
        {% endif %}

        {% if person.forge_account %}
            <strong>{% trans "GitLab account:" %}</strong>
            <a href="{{ person.forge_account_url }}" target="_blank">@{{ person.forge_account }}</a>
            <br>
        {% endif %}

        {% if person.forum_account %}
            <strong>{% trans "Discourse account:" %}</strong>
            <a href="{{ person.forum_account_url }}" target="_blank">@{{ person.forum_account }}</a>
            <br>
        {% endif %}

        {% if person.im_username %}
            <strong>{% trans "Matrix account:" %}</strong>
            <a target="_blank" href="https://matrix.to/#/{{ person.im_username }}">{{ person.im_username }}</a>
            <br>
        {% endif %}

        {% if person.auth_token and on_own_page %}
            <strong>{% trans "Authentication token:" %}</strong>
            <code id="person_auth_token">{{ person.auth_token }}</code>
        {% endif %}
    </div>
</div>

people/templates/people/_includes/person_select_site_language.html
{% if on_own_page %}
    <form action="{% url "set_language" %}" method="post">
        {% csrf_token %}
        <h2>{% trans "Site Language" %}</h2>
        <div class="input-group">
            <label class="input-group-text" for="select-site-language">{% trans 'Site Language' %}</label>
            <select id="select-site-language" class="form-select" name="language">
                {% for lang in all_languages %}
                    <option value="{{ lang.0 }}"
                            {% if lang.0 == LANGUAGE_CODE %}selected="selected"{% endif %}>{{ lang.1 }}
                    </option>
                {% endfor %}
            </select>
            <input class="btn btn-action" type="submit" value="{% trans 'Choose' %}"/>
        </div>
    </form>
{% endif %}

people/templates/people/_includes/person_team_membership.html
{% load stats_extras %}

<h2>{% trans "Team membership" %}</h2>
<ul id="list-person-member-of-teams" class="list-group">
    {% for role in person.role_set.all %}
        {% with role.get_role_display as role_name_display %}
            <li id="person-member-of-{{ role.team.name|slugify }}-team"  class="list-group-item">
                <form method="post" class="d-flex justify-content-between"
                      action="{% url 'person_team_leave' role.team.name %}">
                    <div class="float-start">
                        <p class="text mb-1 mt-1">
                            {% blocktrans trimmed with team_name_url=role.team|linked_with:role.team.get_description|safe role_name=role.role|slugify team_name=role.team.name|slugify %}
                                <span id="role-{{ role_name }}-in-{{ team_name }}-team" class="badge text-bg-secondary">{{ role_name_display }}</span> − {{ team_name_url }}
                            {% endblocktrans %}
                        </p>
                    </div>
                    <div class="float-end d-flex align-items-center">
                        <a class="btn btn-primary px-3 py-0 me-1" href="{{ role.team.get_absolute_url }}">
                            <i class="fa fa-group me-1"></i> {% blocktrans with team_name=role.team.get_description %}Go to “{{ team_name }}” team{% endblocktrans %}
                        </a>
                        {% if on_own_page and on_people_manage_team_membership_view %}
                            {% csrf_token %}
                            {% with role.team.description as team_name %}
                                {% blocktrans asvar leave_team_message %}Are you sure you want to leave the {{ team_name }} team?{% endblocktrans %}
                                <button type="submit" class="btn btn-danger px-3 py-0 ms-1"
                                        onclick="return confirm('{{ leave_team_message }}')">
                                    <i class='fa fa-trash me-1'></i> {% trans 'Leave' %}
                                </button>
                            {% endwith %}
                        {% endif %}
                    </div>
                </form>
            </li>
        {% endwith %}
    {% endfor %}
</ul>