api/urls.py
from django.urls import path

from . import views

complete_translatable_path = (
    "modules/<name:module_name>/branches/<path:branch_name>/domains/<name:domain_name>/languages/<locale:lang>"
)

urlpatterns = [
    path("", views.APIHomeView.as_view(), name="api-v1-home"),
    # Liveliness checks
    path("check/", views.check, name="api-v1-check"),
    # Modules
    path("modules/", views.ModulesView.as_view(), name="api-v1-list-modules"),
    path("modules/<name:module_name>", views.ModuleView.as_view(), name="api-v1-info-module"),
    path(
        "modules/<name:module_name>/branch/<path:branch_name>",
        views.ModuleBranchView.as_view(),
        name="api-v1-info-module-branch",
    ),
    # Teams
    path("teams/", views.TeamsView.as_view(), name="api-v1-list-teams"),
    path("teams/<locale:team_name>", views.TeamView.as_view(), name="api-v1-info-team"),
    # Languages
    path("languages/", views.LanguagesView.as_view(), name="api-v1-list-languages"),
    # Releases
    path("releases/", views.ReleasesView.as_view(), name="api-v1-list-releases"),
    path("releases/<name:release>", views.ReleaseView.as_view(), name="api-v1-info-release"),
    path("releases/<name:release>/stats", views.ReleaseStatsView.as_view(), name="api-v1-info-release-stats"),
    path(
        "releases/<name:release>/languages/<locale:locale>",
        views.ReleaseLanguageView.as_view(),
        name="api-v1-info-release-language",
    ),
    # Vertimus workflow
    path(complete_translatable_path, views.ModuleLangStatsView.as_view(), name="api-v1-module-in-lang-statistics"),
    # APIs to reserve translation and upload translation, as could be used by an external translation tool.
    path(
        f"{complete_translatable_path}/reserve", views.ReserveTranslationView.as_view(), name="api-v1-reserve-module"
    ),
    path(f"{complete_translatable_path}/upload", views.UploadTranslationView.as_view(), name="api-v1-upload-file"),
    # Notifications from the software forge. Read the documentation to see how to trigger this endpoint.
    path(
        "modules/<name:module_name>/branches/<path:branch_name>/ping",
        views.refresh_module_branch,
        name="api-v1-refresh-module-branch",
    ),
]

damnedlies/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path, register_converter
from django.urls.converters import StringConverter
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView
from django.views.static import serve

from common import views as common_views
from stats import views as stats_views


class LocaleConverter(StringConverter):
    regex = "[-_a-zA-Z@]+"


class NameConverter(StringConverter):
    """Converter for module, branch, or domain names."""

    regex = r"[-~\w\+\.]+"


register_converter(LocaleConverter, "locale")
register_converter(NameConverter, "name")
module_branch_domain = "<name:module_name>/<path:branch_name>/<name:domain_name>"

urlpatterns = [
    path("", common_views.index, name="home"),
    path("about/", common_views.about, name="about"),
    path("login/", common_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", require_POST(auth_views.LogoutView.as_view()), name="logout"),
    path("register/", common_views.site_register, name="register"),
    re_path(r"^help/(?P<topic>\w+)/(?P<modal>[0-1])?/?$", common_views.help_view, name="help"),
    path(
        "register/success/",
        TemplateView.as_view(template_name="registration/register_success.html"),
        name="register_success",
    ),
    path("register/activate/<slug:key>", common_views.activate_account, name="register_activation"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<slug:uidb64>/<slug:token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    # Webhook endpoint
    path("pull_code/", common_views.pull_code),
    path("teams/", include("teams.urls")),
    path("people/", include("people.urls")),
    # users is the hardcoded url in the contrib.auth User class, making it identical to /people
    path("users/", include("people.urls")),
    path("languages/", include("languages.urls")),
    path("vertimus/", include("vertimus.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/", admin.site.urls),
    path("rss/", include("feeds.urls")),
    path("api/v1/", include("api.urls")),
]

urlpatterns += [
    re_path(r"^module/(?P<return_format>(html|json|xml))?/?$", stats_views.modules, name="modules"),
    path("module/po/%s/<filename>" % module_branch_domain, stats_views.dynamic_po, name="dynamic_po"),
    path("module/<name:module_name>/", stats_views.module, name="module"),
    path("module/<name:module_name>/edit/branches/", stats_views.module_edit_branches, name="module_edit_branches"),
    path("branch/<int:branch_id>/refresh/", stats_views.branch_refresh, name="branch_refresh"),
    path(
        "module/<name:module_name>/<name:potbase>/<path:branch_name>/<locale:langcode>/images/",
        stats_views.docimages,
        name="docimages",
    ),
    re_path(r"^releases/(?P<format>(html|json|xml))?/?$", stats_views.releases, name="releases"),
    re_path(r"^releases/(?P<release_name>[\w-]+)/(?P<format>(html|xml))?/?$", stats_views.release, name="release"),
    path("releases/compare/<dtype>/<path:rels_to_compare>/", stats_views.compare_by_releases, name="release-compare"),
    # Ajax URLs
    path("module/<name:module_name>/branch/<path:branch_name>/", stats_views.ajax_module_branch, name="module_branch"),
]

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

if settings.STATIC_SERVE:
    urlpatterns += [
        path("media/<path:path>", serve, kwargs={"document_root": settings.MEDIA_ROOT}),
        path("POT/<path:path>", serve, kwargs={"document_root": settings.POT_DIR}),
        path("HTML/<path:path>", serve, kwargs={"document_root": settings.SCRATCHDIR / "HTML"}),
    ]

teams/urls.py
from django.urls import path, re_path

from teams import views

urlpatterns = [
    re_path(r"^(?P<format_requested>(xml|json))?/?$", views.teams, name="teams"),
    path("<locale:team_slug>/", views.team, name="team_slug"),
    path("<locale:team_slug>/edit/", views.team_edit, name="team_edit"),
    path("<locale:team_slug>/join/", views.connected_user_join_team, name="team_join"),
    path("<locale:team_slug>/leave/", views.connected_user_leave_team, name="team_leave"),
]

teams/models.py
from datetime import timedelta
from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone, translation
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy

from common.utils import send_mail
from people.models import Person

if TYPE_CHECKING:
    from languages.models import Language


class TeamManager(models.Manager):
    def all_with_coordinator(self: "TeamManager") -> QuerySet:
        """
        Returns all teams with the coordinator already prefilled. Use that
        function to reduce the size of extracted data and the numbers of objects
        built or use all_with_roles() if you need information about the other
        roles.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(role="coordinator")
        role_dict = {}

        for role in roles:
            role_dict.setdefault(role.team_id, []).append(role.person)

        for team in teams:
            try:
                team.roles = {"coordinator": role_dict[team.id]}
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams

    def all_with_roles(self: "TeamManager") -> QuerySet:
        """
        This method prefills team.coordinator/committer/reviewer/translator to
        reduce subsequent database access.
        """
        teams = self.all()
        roles = Role.objects.select_related("person").filter(is_active=True)
        role_dict = {}

        for role in roles:
            if role.team_id not in role_dict:
                role_dict[role.team_id] = [role]
            else:
                role_dict[role.team_id].append(role)

        for team in teams:
            try:
                for role in role_dict[team.id]:
                    team.fill_role(role.role, role.person)
            except KeyError:
                # Abnormal because a team must have a coordinator but of no
                # consequence
                pass
        return teams


class Team(models.Model):
    """The lang_code is generally used for the name of the team."""

    name = models.CharField(max_length=80)
    description = models.TextField()
    use_workflow = models.BooleanField(default=True)
    presentation = models.TextField(blank=True, verbose_name=_("Presentation"))
    members = models.ManyToManyField(Person, through="Role", related_name="teams")
    webpage_url = models.URLField(null=True, blank=True, verbose_name=_("Web page"))
    mailing_list = models.EmailField(null=True, blank=True, verbose_name=_("Mailing list"))
    mailing_list_subscribe = models.URLField(null=True, blank=True, verbose_name=_("URL to subscribe"))
    objects = TeamManager()

    class Meta:
        db_table = "team"
        ordering = ("description",)

    def __init__(self: "Team", *args, **kwargs) -> None:  # noqa ANN003
        models.Model.__init__(self, *args, **kwargs)
        self.roles: dict[str, list[Person]] = {}

    def __str__(self: "Team") -> str:
        return self.description

    def get_absolute_url(self: "Team") -> str:
        return reverse("team_slug", args=[self.name])

    def can_edit(self: "Team", user: "Person") -> bool:
        """Return True if user is allowed to edit this team
        user is a User (from request.user), not a Person
        """
        return user.is_authenticated and user.username in [p.username for p in self.get_coordinators()]

    def fill_role(self: "Team", role: str, person: "Person") -> None:
        """Used by TeamManager to prefill roles in team"""
        if not self.roles:
            self.roles = {"coordinator": [], "committer": [], "reviewer": [], "translator": []}
        self.roles[role].append(person)

    def get_description(self: "Team") -> str:
        return _(self.description)

    def get_languages(self: "Team") -> tuple["Language"]:
        return tuple(self.language_set.all())

    def get_members_by_role_exact(self: "Team", role: str, only_active: bool = True) -> list[Person]:
        """Return a list of active members"""
        try:
            return self.roles[role]
        except KeyError:
            if only_active:
                members = Person.objects.filter(role__team__id=self.id, role__role=role, role__is_active=True)
            else:
                members = Person.objects.filter(role__team__id=self.id, role__role=role)
            return list(members)

    def get_coordinators(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("coordinator", only_active=False)

    def get_committers_exact(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("committer")

    def get_reviewers_exact(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("reviewer")

    def get_translators_exact(self: "Team") -> list[Person]:
        return self.get_members_by_role_exact("translator")

    def get_members_by_roles(self: "Team", roles: list[str], only_active: bool = True) -> list[Person]:
        """Requires a list of roles in argument"""
        try:
            members = []
            for role in roles:
                members += self.roles[role]
        except KeyError:
            if only_active:
                members = Person.objects.filter(role__team__id=self.id, role__role__in=roles, role__is_active=True)
            else:
                members = Person.objects.filter(role__team__id=self.id, role__role__in=roles)
        return list(members)

    def get_committers(self: "Team") -> list[Person]:
        return self.get_members_by_roles(["coordinator", "committer"])

    def get_reviewers(self: "Team") -> list[Person]:
        return self.get_members_by_roles(["coordinator", "committer", "reviewer"])

    def get_translators(self: "Team") -> list[Person]:
        """Don't use get_members_by_roles to provide an optimization"""
        try:
            members = []
            for role in ["coordinator", "committer", "reviewer", "translator"]:
                members += self.roles[role]
        except KeyError:
            # Not necessary to filter as for other roles
            members = list(self.members.all())
        return members

    def get_inactive_members(self: "Team") -> list[Person]:
        """Return the inactive members"""
        return list(Person.objects.filter(role__team__id=self.id, role__is_active=False))

    def send_mail_to_coordinator(
        self: "Team", subject: str, message: str, message_kwargs: dict[str, Any] | None = None
    ) -> None:
        """Send a message to the coordinator, in her language if available
        and if subject and message are lazy strings"""
        recipients = [pers.email for pers in self.get_coordinators() if pers.email]
        if not recipients:
            return
        with translation.override(self.language_set.first().locale):
            message = "%s\n--\n" % (message % (message_kwargs or {}),)  # noqa: UP031
            message += _("This is an automated message sent from %s.") % settings.SITE_DOMAIN
            send_mail(str(subject), message, to=recipients, headers={settings.EMAIL_HEADER_NAME: "coordinator-mail"})


class FakeTeam:
    """
    This is a class replacing a Team object when a language
    has no team attached.
    """

    fake = 1

    def __init__(self: "FakeTeam", language: "Language") -> None:
        self.language = language
        self.description = _("No team for locale %s") % self.language.locale

    def get_absolute_url(self: "FakeTeam") -> str:
        return reverse("team_slug", args=[self.language.locale])

    def can_edit(self: "FakeTeam", _: "Person") -> bool:  # noqa PLR6301
        return False

    def get_description(self: "FakeTeam") -> str:
        return self.language.locale

    def get_languages(self: "FakeTeam") -> str:
        return _(
            self.language,
        )

    def get_coordinators(self: "FakeTeam") -> list[Person]:  # noqa PLR6301
        return []


ROLE_CHOICES = (
    ("translator", gettext_lazy("Translator")),
    ("reviewer", gettext_lazy("Reviewer")),
    ("committer", gettext_lazy("Committer")),
    ("coordinator", gettext_lazy("Coordinator")),
)


class Role(models.Model):
    """
    This is the intermediary class between Person and Team to attribute roles to
    Team members.
    """

    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    role = models.CharField(max_length=15, choices=ROLE_CHOICES, default="translator")
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "role"
        unique_together = ("team", "person")

    def __str__(self: "Role") -> str:
        return f"{self.person.name} is {self.role} in {self.team.description} team"

    @classmethod
    def inactivate_unused_roles(cls: "Role") -> None:
        """Inactivate the roles when login older than 180 days"""
        last_login = timezone.now() - timedelta(days=30 * 6)
        cls.objects.filter(person__last_login__lt=last_login, is_active=True).update(is_active=False)

teams/templates/teams/team_base.html
{# Variables 'team' and 'language' must be defined prior to calling this template #}

{% with team.get_description as lang %}
    <div class="row">
        <div class="col-md-5 col-sm-6">
            <h2>{% trans "Details" %}
                {% if can_edit_details %}
                    <a href="{% url 'team_edit' team.name %}">
                        <img src="{% static 'img/edit.png' %}" alt="Edit">
                    </a>
                {% endif %}
            </h2>

            <dl>
                {% if team.webpage_url %}
                    <dt>{% blocktrans %}{{ lang }} Translation Team Page:{% endblocktrans %}</dt>
                    <dd><a href="{{ team.webpage_url }}">{{ team.webpage_url }}</a></dd>
                {% endif %}

                <dt>{% trans "Bug reporting:" %}</dt>
                <dd>
                    <ul class="foot">
                        <li><a href="{{ language.bugs_url_enter|safe }}">{% trans "Report Bug in Translation" %}</a></li>
                        <li><a href="{{ language.bugs_url_show|safe }}">{% trans "Show Existing Bugs" %}</a></li>
                    </ul>
                </dd>

                {% if team.mailing_list %}
                    <dt>{% trans "Mailing List:" %}</dt>
                    <dd>
                        <ul class="foot">
                            <li><a href="mailto:{{ team.mailing_list }}">{% trans "Send e-mail to the list" %}</a></li>
                            {% if team.mailing_list_subscribe %}
                                <li><a href="{{ team.mailing_list_subscribe }}">{% trans "Subscribe" %}</a></li>
                            {% endif %}
                        </ul>
                    </dd>
                {% endif %}
            </dl>
        </div>

        <div class="col-md-7 col-sm-6">
            <h2>{% trans "Coordinator" %}</h2>
            {% for person in team.get_coordinators %}
                {% include "people/_includes/person_overview.html" %}
            {% empty %}
                <p><em>{% trans "This team has currently no coordinator." %}<br>
                    {% blocktrans with link="https://wiki.gnome.org/TranslationProject/TeamCoordinatorResponsibilities" %}See <a href="{{ link }}">the GTP Wiki</a> for more information about coordinatorship.{% endblocktrans %}</em></p>
            {% endfor %}
        </div>
    </div>
{% endwith %}

teams/templates/teams/team_detail.html
{% extends "base.html" %}
{% load stats_extras %}

{% block extrahead %}
    <link rel="alternate" type="application/rss+xml"
          title="{% blocktrans with team.get_description as lang %}Last actions made by the {{ lang }} team of the GNOME Translation Project{% endblocktrans %}"
          href="/rss/teams/{{ team.name }}" />

    <style>
        img.toggler { cursor: pointer; }
        div#togglable-inactive { display: none; }
    </style>
    <script>
        /**
         * Collapse or reduce the container that holds the archived releases information.
         * @param ${String} locale the locale (ISO-639-1) of the target language
         */
        function collapse_or_reduce_archived_modules(locale) {
            let collapse_or_reduce_button = document.getElementById(`archived-releases-in-${locale}-toggler`);
            let archived_modules_container = document.getElementById(`archived-releases-in-${locale}`);
            let archived_should_be_expanded = archived_modules_container.classList.contains("d-none")
            if (archived_should_be_expanded) {
                let xhr = new XMLHttpRequest();
                xhr.open('GET', archived_modules_container.dataset.url);
                xhr.onload = function() {
                    archived_modules_container.classList.replace("d-none", "d-block");
                    archived_modules_container.innerHTML = xhr.response;
                    collapse_or_reduce_button.children[0].classList.replace("fa-expand", "fa-compress");
                }
                xhr.send();
            } else {
                archived_modules_container.classList.replace("d-block", "d-none");
                collapse_or_reduce_button.children[0].classList.replace("fa-compress", "fa-expand");
            }
        }
    </script>
{% endblock %}

{% block title %}{{ team.get_description }}{% endblock %}

{% block content %}
    <div class="col-xs-12">
        {% if not team.fake %}
            {% with team.get_description as language %}
                {% if user_is_member %}
                    <a class="btn btn-danger float-end mt-md-2 py-0 py-md-1" data-bs-toggle="modal" data-bs-target="#modal-leave-team"
                       href="{% url 'team_leave' team_slug=team.name %}">
                        <i class="fa fa-times me-2" aria-hidden="true"></i>{% translate "Leave" %}
                    </a>
                    </div>
                    <div class="modal modal-md fade generic-modal" id="modal-leave-team" data-bs-backdrop="static"
                         data-bs-keyboard="false"
                         tabindex="-1" aria-labelledby="modal-leave-team-label" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <span class="modal-title fs-3 text-center mx-auto" id="modal-leave-team-label">
                                        <i class="fa fa-2x fa-trash me-2 bg-danger p-3 rounded-circle text-white" style="width: 80px; height: 80px; " aria-hidden="true"></i>
                                        <br />
                                        <span class="text-danger">{% blocktranslate %}Leave the “<b>{{ language }}</b>” team{% endblocktranslate %}</span>
                                    </span>
                                </div>
                                <div class="modal-body">
                                    <p>{% translate "By leaving the team, you will:" %}</p>
                                    <ol>
                                        <li>{% translate "Stop being able to contribute." %}</li>
                                        <li>{% translate "Lose the right to translate." %}</li>
                                        <li>{% translate "Lose your rights as a reviewer or committer." %}</li>
                                    </ol>
                                </div>
                                <div class="modal-footer d-flex justify-content-between">
                                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">{% translate "Cancel" %}</button>
                                    <form method="post" action="{% url 'team_leave' team_slug=team.name %}">
                                        {% csrf_token %}
                                        <button type="submit"  class="btn btn-danger">
                                            <i class="fa fa-times me-2" aria-hidden="true"></i>
                                            {% translate "Leave the team" %}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <form method="post" action="{% url 'team_join' team_slug=team.name %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary float-end mt-md-2 py-0 py-md-1">
                            <i class="fa fa-user-plus me-2" aria-hidden="true"></i>{% translate "Join" %}
                        </button>
                    </form>
                {% endif %}
                <h1>{% blocktrans %}{{ language }} Translation Team{% endblocktrans %}</h1>
            {% endwith %}

            {% if team.presentation %}
                <div>{{ team.presentation|markdown }}</div>
                <hr />
            {% endif %}
            {% with team.get_languages.0 as language %}
                {% include "teams/team_base.html" %}
            {% endwith %}
        {% else %}
            <h1>{{ team.get_description }}</h1>
            <p>
                <em>
                    {% blocktrans trimmed %}
                        There is currently no established team for this language.
                        See <a href="https://wiki.gnome.org/TranslationProject/StartingATeam">the GTP Wiki</a> to get
                        more information about the process of building a new translation team.
                    {% endblocktrans %}
                </em>
            </p>
        {% endif %}

        {% for lang in team.get_languages %}

            <h2>{{ lang.get_name }} <code>({{ lang.locale }})</code></h2>

            {% if user.is_authenticated %}
                <div class="right"><a class="btn btn-action" href="{% url 'activity_by_language' lang.locale %}">{% trans "Current activities" %}</a></div>
            {% endif %}

            <p><strong>{% trans "Plural forms:" %}</strong> {{ lang.get_plurals }}</p>

            {% with 1 as show_all_modules_line %}
                {% with lang.get_release_statistics_in_a_given_language as stats %}
                    {% include "languages/_includes/language_release_summary.html" %}
                {% endwith %}
            {% endwith %}

            <h3>
                <button id="archived-releases-in-{{ lang.locale|escape_at_sign }}-toggler"
                        title="{% trans 'Show/hide archived translations' %}"
                        onclick="collapse_or_reduce_archived_modules('{{ lang.locale }}')"
                        class="btn mx-1 px-3">
                    <i class="fa fa-expand"></i>
                </button>
                {% trans "Archives" %}
            </h3>

            <div
                id="archived-releases-in-{{ lang.locale|escape_at_sign }}"
                class="d-none"
                data-url="{% url 'language_release_archives' lang.locale %}">
            </div>

        {% endfor %}

        {% if not team.fake %}
            <h2>{% trans "Team membership" %}</h2>
            {% comment %}
            	mem_groups contains the team members depending on their group: committer, reviewer and/or translator.
            {% endcomment %}
            {% for group in mem_groups %}
                <h3 >
                    {% if group.id == 'inactive_members' and group.members %}
                        <button id="{{ group.id }}" class="btn mx-1 px-3"
                                title="{% trans 'Show or hide inactive team members' %}"
                                data-bs-toggle="collapse" href="#archived-team-members-{{ forloop.counter }}" role="button"
                                aria-expanded="false" aria-controls="archived-team-members-{{ forloop.counter }}">
                            <i class="fa fa-expand"></i>
                        </button>
                    {% endif %}
                    {{ group.title }}
                </h3>
                <div>
                    {% if group.form %}
                        <form action="{{ request.path }}" method="POST">
                            {% csrf_token %}
                            <ul class="foot">
                                {% for field in group.form.get_fields %}
                                    <li>{{ field.label|safe }} {{ field }}</li>
                                {% endfor %}
                            </ul>
                            {{ group.form.form_type }}
                            <input type="submit" value="{% trans 'Apply modifications' %}">
                        </form>
                    {% else %}
                            {% comment %}
                                The group is inactive, so anyway, we hide the members in a collapsable element.
                            {% endcomment %}
                        {% if group.id == 'inactive_members' and group.members %}
                            <div class="collapse" id="archived-team-members-{{ forloop.counter }}">
                                {% include "teams/_includes/list_team_members.html" with group=group %}
                            </div>
                        {% else %}
                            {% include "teams/_includes/list_team_members.html" with group=group %}
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

teams/templates/teams/team_edit.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block title %}{{ team.get_description }}{% endblock %}

{% block extrahead %}
    <script src="{% static 'js/autosize.min.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            autosize(document.querySelector('#id_presentation'));
        }, false);
    </script>
{% endblock %}

{% block content %}
    <div class="col-xs-12">
        <h1>{% blocktrans with team.get_description as lang %}{{ lang }} Translation Team{% endblocktrans %}</h1>

        <form action="{{ request.path }}" method="POST" class="djform form">
            {% csrf_token %}
            <table>
                {% if form.coordinatorship %}
                    <tr>
                        <th>{{ form.coordinatorship.label }}:</th>
                        <td>{{ form.coordinatorship.errors }}{{ form.coordinatorship }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <th>{{ form.webpage_url.label }}:</th>
                    <td>{{ form.webpage_url.errors }}{{ form.webpage_url }}</td>
                </tr>
                <tr>
                    <th>{{ form.mailing_list.label }}:</th>
                    <td>{{ form.mailing_list.errors }}{{ form.mailing_list }}</td>
                </tr>
                <tr>
                    <th>{{ form.mailing_list_subscribe.label }}:</th>
                    <td>{{ form.mailing_list_subscribe.errors }}{{ form.mailing_list_subscribe }}</td>
                    <tr>
                        <th></th>
                        <td>
                            {{ form.use_workflow }}
                            <label for="id_use_workflow">{% trans "This team is using the translation workflow" %}</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="help">&nbsp</span><br/>{{ form.presentation.label }}:
                        </th>
                        <td>
                            {{ form.presentation.label.errors }}
                            <span
                                class="help">{% trans "This content may use <a href='https://en.wikipedia.org/wiki/Markdown'>Markdown</a> syntax" %}<br/></span>
                            {{ form.presentation }}
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="{% trans 'Save' %}"/></td>
                    </tr>
                </table>
            </form>
        </div>
{% endblock %}